<a href="https://colab.research.google.com/github/arshad-huh/Numpy-Module/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([54, 91,  5, 88, 90, 42, 81, 12, 96, 10,  1, 27, 53, 74, 24])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[81, 15,  8, 66],
       [46, 12, 56, 46],
       [81, 85, 90, 57],
       [48, 12, 10, 41],
       [99, 32, 84, 68],
       [ 4, 33, 71, 82]])

In [3]:
np.sort(a)[::-1]

array([96, 91, 90, 88, 81, 74, 54, 53, 42, 27, 24, 12, 10,  5,  1])

In [4]:
np.sort(b,axis=0)

array([[ 4, 12,  8, 41],
       [46, 12, 10, 46],
       [48, 15, 56, 57],
       [81, 32, 71, 66],
       [81, 33, 84, 68],
       [99, 85, 90, 82]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 54,  91,   5,  88,  90,  42,  81,  12,  96,  10,   1,  27,  53,
        74,  24, 200])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [6]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [7]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [8]:
# code
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[11],
       [53],
       [28],
       [50],
       [38],
       [37],
       [94],
       [92],
       [ 5],
       [30],
       [68],
       [ 9],
       [78],
       [ 2],
       [21]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

np.where(condition, if true, if false)

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [9]:
a

array([54, 91,  5, 88, 90, 42, 81, 12, 96, 10,  1, 27, 53, 74, 24])

In [10]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  4,  6,  8, 12, 13]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [13]:
# code
a

array([54, 91,  5, 88, 90, 42, 81, 12, 96, 10,  1, 27, 53, 74, 24])

In [14]:
np.argmax(a)

8

In [15]:
b

array([[81, 15,  8, 66],
       [46, 12, 56, 46],
       [81, 85, 90, 57],
       [48, 12, 10, 41],
       [99, 32, 84, 68],
       [ 4, 33, 71, 82]])

In [16]:
np.argmax(b,axis=0)

array([4, 2, 2, 5])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [ ]:
# np.argmin
np.argmin(a)

13

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [17]:
np.cumsum(b)

array([  81,   96,  104,  170,  216,  228,  284,  330,  411,  496,  586,
        643,  691,  703,  713,  754,  853,  885,  969, 1037, 1041, 1074,
       1145, 1227])

In [18]:
# np.cumprod
np.cumprod(a)

array([                  54,                 4914,                24570,
                    2162160,            194594400,           8172964800,
               662010148800,        7944121785600,      762635691417600,
           7626356914176000,     7626356914176000,   205911636682752000,
       -7533427329523695616, -4071300173466927104, -5477483794658492416])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [19]:
a

array([54, 91,  5, 88, 90, 42, 81, 12, 96, 10,  1, 27, 53, 74, 24])

In [26]:
np.percentile(a,50)

53.0

In [ ]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [27]:
np.histogram(a,bins=[0,25,50,75,100])

(array([5, 2, 3, 5]), array([  0,  25,  50,  75, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([54, 91,  5, 88, 90, 42, 81, 12, 96, 10,  1, 27, 53, 74, 24])

In [31]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90, 10])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.flip(b,axis=1)

array([[ 6, 42, 52, 12],
       [55, 47, 18, 29],
       [ 9, 83, 93, 61],
       [85, 44, 63, 38],
       [72, 31, 87,  8],
       [ 7,  2, 71, 40]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [33]:
a

array([54, 91,  5, 88, 90, 42, 81, 12, 96, 10,  1, 27, 53, 74, 24])

In [34]:
np.put(a,[0,1],[110,530])

In [35]:
a

array([110, 530,   5,  88,  90,  42,  81,  12,  96,  10,   1,  27,  53,
        74,  24])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [36]:
a

array([110, 530,   5,  88,  90,  42,  81,  12,  96,  10,   1,  27,  53,
        74,  24])

In [37]:
np.delete(a,[0,2,4])

array([530,  88,  42,  81,  12,  96,  10,   1,  27,  53,  74,  24])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [38]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
np.intersect1d(m,n)

array([3, 4, 5])

np.setdiff1d(n, m) ==>
This function finds the elements in the first input array (n) that are not present in the second input array (m).

In [40]:
np.setdiff1d(n, m)

array([6, 7])

np.setxor1d(m,n) ==> Finds the symmetric difference between the two sets. Think of it as all the elements that are unique to either m or n, but not present in both.

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

### np.swapaxes

In [48]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
swapped_matrix = np.swapaxes(matrix, 0, 1)

print(f"Original matrix:\n{matrix}")
print(f"Swapped matrix:\n{swapped_matrix}")

Original matrix:
[[1 2 3]
 [4 5 6]]
Swapped matrix:
[[1 4]
 [2 5]
 [3 6]]


### np.uniform

Parameters:

low: The lower bound of the range for the random numbers (inclusive).

high: The upper bound of the range (exclusive).

size: (Optional) The shape of the desired array of random numbers. By default, it's a single value.

In [51]:
random_numbers = np.random.uniform(0, 1, size=10)

print(random_numbers)

[0.09615954 0.97359195 0.98283447 0.21030668 0.51268277 0.13521908
 0.66051578 0.99282782 0.2252904  0.38634915]


In [ ]:
# 19. np.count_nonzero

### np.tile

input: The array you want to replicate (the tile).

reps: A tuple or integer specifying how many times to repeat the tile in each dimension.

Optional: Additional arguments for fine-tuning the tiling behavior.

In [54]:
single_element = np.array([5])
repeated_element = np.tile(single_element, (3, 4))

print(repeated_element)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [56]:
black_tile = np.array([0])
white_tile = np.array([1])

checkerboard = np.tile((black_tile, white_tile), (2, 2))

print(checkerboard)

[[0 0]
 [1 1]]


### np.repeat

In [55]:
chili_flakes = np.array([1, 2, 3])
spicy_dish = np.repeat(chili_flakes, 3)

print(spicy_dish)

[1 1 1 2 2 2 3 3 3]


In [59]:
drum_beat = np.array([1, 0])
repeated_beat = np.repeat(drum_beat, 8, axis=0)

print(repeated_beat)

[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]


### np.allclose

a1: The first array to be compared.

a2: The second array to be compared.

rtol: The relative tolerance (a percentage difference allowed).

atol: The absolute tolerance (a fixed difference allowed).

In [63]:
sensor1_data = np.array([1.01, 2.02, 3.04])
sensor2_data = np.array([1.00, 2.01, 3.03])

are_close = np.allclose(sensor1_data, sensor2_data, rtol=0.02)

print(f"Sensor readings similar? {are_close}")

Sensor readings similar? True


In [67]:
forecast1 = np.array([105, 110, 115])
forecast2 = np.array([104, 112, 117])

are_similar = np.allclose(forecast1, forecast2, atol=2)

print(f"Forecasts close enough? {are_similar}")

Forecasts close enough? True
