<a href="https://colab.research.google.com/github/arshad-huh/Numpy-Module/blob/main/practice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [28]:
# i
arr = np.random.randint(0, 100, (3,4))
print("Array:\n", arr)

# ii
sorted_arr = np.sort(arr)
print("Sorted Array:\n", sorted_arr)

# iii
sorted_col = np.sort(arr[:, 1])
arr[:, 1] = sorted_col
print("Sorted Array in 2nd Column:\n", arr)

# iv
sorted_elements = np.sort(np.ravel(arr))
sorted_ele_arr = sorted_elements.reshape(3,4)
print("Sorted based on elements value:\n", sorted_ele_arr)

Array:
 [[22 99 34  7]
 [72 89 39 42]
 [33 26 97 75]]
Sorted Array:
 [[ 7 22 34 99]
 [39 42 72 89]
 [26 33 75 97]]
Sorted Array in 2nd Column:
 [[22 26 34  7]
 [72 89 39 42]
 [33 99 97 75]]
Sorted based on elements value:
 [[ 7 22 26 33]
 [34 39 42 72]
 [75 89 97 99]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [66]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])

print("Marks:\n", marks)

# i
updated_marks = np.column_stack((marks, extra_subject))
print("Updated Marks:\n", updated_marks)


# ii
# Two new students' records
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

updated_marks2 = np.vstack((updated_marks, rec1, rec2))

print("Marks with 2 new students added:\n", updated_marks2)

# iii
updated_marks3 = np.column_stack((updated_marks2, np.sum(updated_marks2, axis=1)))

print("Marks with Sum column:\n", updated_marks3)


# iv
sorted_indices = np.argsort(updated_marks3[:, -1])[::-1]
updated_marks4 = updated_marks3[sorted_indices]

print("Sorted Marks(non-ascending order) on total marks column:\n", updated_marks4)

Marks:
 [[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]
Updated Marks:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
Marks with 2 new students added:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
Marks with Sum column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
Sorted Marks(non-ascending order) on total marks column:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [71]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

arr_col_wise = np.unique(arr, axis=0)
arr_row_wise = np.unique(arr, axis=1)

print(f"Unique Array Column Wise:\n {arr_col_wise}")
print(f"Unique Array Row Wise:\n {arr_row_wise}")

Unique Array Column Wise:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
Unique Array Row Wise:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [72]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flipped_array = np.flip(arr, axis=None)

print("Original Array:")
print(arr)

print("\nFlipped Array along both axes:")
print(flipped_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Array along both axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [81]:
arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

x = 6

rows_with_larger_elements = np.any(arr > x, axis=1)

row_numbers = np.where(rows_with_larger_elements)[0]

print("Row numbers with elements larger than", x, ":", row_numbers)

[False  True False  True]
(array([1, 3]),)
Row numbers with elements larger than 6 : (array([1, 3]),)


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [85]:
arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

arr.ravel()

array([ 1,  2,  3,  4,  5, 10, -3, 30,  4,  5,  3,  2,  5, -4,  5,  9,  7,
        3,  6,  5])

In [86]:
arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

arr.flatten()

array([ 1,  2,  3,  4,  5, 10, -3, 30,  4,  5,  3,  2,  5, -4,  5,  9,  7,
        3,  6,  5])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [88]:
arr = np.array([4, 2, 7, 1, 5, 9, 2, 6, 5, 3, 5])

min_index = np.argmin(arr)
max_index = np.argmax(arr)

min_element = arr[min_index]
max_element = arr[max_index]

arr_without_min_max = np.delete(arr, [min_index, max_index])

print("Original Array:")
print(arr)

print("\nMinimum Element:", min_element)
print("Maximum Element:", max_element)

print("\nArray without Minimum and Maximum Elements:")
print(arr_without_min_max)

Original Array:
[4 2 7 1 5 9 2 6 5 3 5]

Minimum Element: 1
Maximum Element: 9

Array without Minimum and Maximum Elements:
[4 2 7 5 2 6 5 3 5]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [101]:
arr = np.array([ 76, 633, 293, 574,  22, 420, 126, 423, 251, 200, 205, 520, 389,
       445, 312, 251, 579, 439, 642, 131])

arr1 = np.clip(arr, a_min=100, a_max=200)
arr2 = np.sort(arr1)
arr3 = np.cumsum(arr2)

print("Original Array:")
print(arr)

print("\nSorted Array:")
print(arr2)

print("\nCumulative Sum of the Sorted Array:")
print(arr3)

Original Array:
[ 76 633 293 574  22 420 126 423 251 200 205 520 389 445 312 251 579 439
 642 131]

Sorted Array:
[100 100 126 131 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]

Cumulative Sum of the Sorted Array:
[ 100  200  326  457  657  857 1057 1257 1457 1657 1857 2057 2257 2457
 2657 2857 3057 3257 3457 3657]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [110]:
arr = np.random.random(10)

arr_rounded = np.round(arr, 3)


min_value = np.percentile(arr_rounded, 0)
max_value = np.percentile(arr_rounded, 100)

percentile_50 = np.percentile(arr_rounded, 50)
percentile_51 = np.percentile(arr_rounded, 51)
difference_51_50 = percentile_51 - percentile_50

print("Original Array:")
print(arr)

print("\nArray Rounded to 3 Decimal Places:")
print(arr_rounded)

print("\nMinimum Value (0th Percentile):", min_value)
print("Maximum Value (100th Percentile):", max_value)

print("\n50th Percentile (Median):", percentile_50)
print("51st Percentile:", percentile_51)
print("Difference between 51st and 50th Percentiles:", difference_51_50)

Original Array:
[0.51698047 0.83896132 0.99258315 0.46137065 0.72554258 0.59741372
 0.84937403 0.70333066 0.57544915 0.03086726]

Array Rounded to 3 Decimal Places:
[0.517 0.839 0.993 0.461 0.726 0.597 0.849 0.703 0.575 0.031]

Minimum Value (0th Percentile): 0.031
Maximum Value (100th Percentile): 0.993

50th Percentile (Median): 0.6499999999999999
51st Percentile: 0.6595399999999999
Difference between 51st and 50th Percentiles: 0.009539999999999993
